### ISSUE TITLE
Extra spaces - HTML with inline CSS does not seem to be structurally equivalent

### ISSUE THREAD

**Issue by jontsai** [mdedetrich/java-premailer-wrapper#2]
I'm seeing, in some cases, that in the rendered HTML after conversion to inline CSS, there are extra spaces between HTML elements, and this is undesirable.

In the source HTML, multiple tags or nodes might be adjoined with no spaces.

For example:
`<span class="red">R</span><span class="orange">O</span><span class="yellow">Y</span><span class="green">G</span><span class="blue">B</span><span class="indigo">I</span><span class="violet">V</span>`

Should generate:
`<span style="color: red">R</span><span style="color: orange">O</span><span  style="color: yellow">Y</span><span  style="color: green">G</span><span  style="color: blue">B</span><span  style="color: aqua">I</span><span  style="color: purple">V</span>`

However, the no-space in between HTML nodes is not preserved. The above (^) example is made up. In my particular use case there are `span` tag siblings on either side of a plain, un-tagged HTML text node. Trying various combinations does not work, and the generated HTML has spaces before and after the text node when rendered.

I noticed that the web-based Premailer conversion tool does not have this issue. http://premailer.dialect.ca/

**Comment by mdedetrich** [comment]
Closing this because I assume its fixed. Reopen it if its not the case
